# Generated by Django 6.0.6 on 2026-07-01 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feasibility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SCL', 'SCL'), ('fiber_home', 'Fiber@Home'), ('bahon', 'Bahon'), ('level3', 'Level3')], max_length=20)),
                ('requested_capacity', models.PositiveIntegerField(help_text='Mbps')),
                ('available_capacity', models.PositiveIntegerField(blank=True, help_text='Mbps', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('partially_confirmed', 'Partially Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feasibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_confirmations', to='feasibility.feasibilityrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('IPT', 'IPT - Internet Protocol Transit'), ('GGC', 'GGC - Google Global Cache'), ('FNA', 'FNA - Facebook Network Appliance'), ('BDIX', 'BDIX - Bangladesh Internet Exchange'), ('CDN', 'CDN - Content Delivery Network')], max_length=10)),
                ('capacity_mbps', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('installation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiber_deployment_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('one_time_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_monthly_charge', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feasibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pricings', to='feasibility.feasibilityrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
