# Generated by Django 6.0.6 on 2026-07-01 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POPLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'POP Location',
            },
        ),
        migrations.CreateModel(
            name='FeasibilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('proprietor_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('requested_capacity', models.PositiveIntegerField(help_text='Capacity in Mbps')),
                ('preferred_nttn', models.CharField(blank=True, choices=[('SCL', 'SCL'), ('fiber_home', 'Fiber@Home'), ('bahon', 'Bahon'), ('level3', 'Level3')], max_length=20)),
                ('supported_nttn', models.JSONField(default=list)),
                ('distance_to_pop_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('air_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('fiber_route_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('estimated_fiber_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('feasible', 'Feasible'), ('feasible_additional_cost', 'Feasible with Additional Cost'), ('not_feasible', 'Not Feasible'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('estimated_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('engineering_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emails_sent', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_requests', to=settings.AUTH_USER_MODEL)),
                ('nearest_pop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feasibility.poplocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
