# Generated by Django 6.0.6 on 2026-08-17 10:09

import django.db.models.deletion
from django.db import migrations, models


def backfill_frq_data(apps, schema_editor):
    FeasibilityRequest = apps.get_model('feasibility', 'FeasibilityRequest')
    for fr in FeasibilityRequest.objects.all():
        updates = []
        if not fr.contact_person and fr.customer_name:
            fr.contact_person = fr.customer_name
            updates.append('contact_person')
        if not fr.frq_number:
            fr.frq_number = f'FRQ-{fr.pk}'
            updates.append('frq_number')
        if updates:
            fr.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility', '0005_nttn_provider_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='customer_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='frq_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FRQ ID'),
        ),
        migrations.AlterField(
            model_name='feasibilityrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('feasible', 'Feasible'), ('feasible_additional_cost', 'Feasible with Additional Cost'), ('not_feasible', 'Not Feasible'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='nttnproviderresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('feasible', 'Feasible'), ('feasible_additional_cost', 'Feasible with Additional Cost'), ('not_feasible', 'Not Feasible'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_requests', to='feasibility.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='feasibility.division'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_requests', to='feasibility.division'),
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='feasibility.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_requests', to='feasibility.upazila'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('division', 'name')},
        ),
        migrations.RunPython(backfill_frq_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feasibilityrequest',
            name='frq_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='FRQ ID'),
        ),
    ]
