# Generated by Django 6.0.6 on 2026-08-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility', '0006_phase1_frq_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilityrequest',
            name='preferred_nttn_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other NTTN Name'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='preferred_nttn_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_requests', to='feasibility.nttnprovider', verbose_name='Preferred NTTN'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='review_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='review_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feasibilityrequest',
            name='frq_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='FRQ ID'),
        ),
        migrations.AlterField(
            model_name='feasibilityrequest',
            name='preferred_nttn',
            field=models.CharField(blank=True, choices=[('SCL', 'SCL'), ('fiber_home', 'Fiber@Home'), ('bahon', 'Bahon'), ('level3', 'Level3')], max_length=30),
        ),
        migrations.CreateModel(
            name='FRQNTTNReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_other_name', models.CharField(blank=True, max_length=100)),
                ('pop_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pop_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('straight_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Distance from customer (km)')),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('feasibility_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nttn_review_entries', to='feasibility.feasibilityrequest')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_entries', to='feasibility.nttnprovider')),
            ],
            options={
                'verbose_name': 'FRQ NTTN Review Entry',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
