# Generated by Django 6.0.6 on 2026-08-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility', '0007_phase2_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Upstream Provider',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='extra_document',
            field=models.FileField(blank=True, null=True, upload_to='wo_docs/', verbose_name='Additional Document'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='nid_back',
            field=models.FileField(blank=True, null=True, upload_to='nid/back/', verbose_name='NID Back'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='nid_front',
            field=models.FileField(blank=True, null=True, upload_to='nid/front/', verbose_name='NID Front'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='sftp_type',
            field=models.CharField(blank=True, choices=[('dedicated', 'Dedicated'), ('shared', 'Shared'), ('colocation', 'Colocation'), ('others', 'Others')], max_length=30, verbose_name='SFTP Type'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='upstream_provider_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Upstream Name'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='wo_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='wo_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Work Order ID'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='wo_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='client_share_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='kloud_share_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='service_type',
            field=models.CharField(choices=[('BW', 'Bandwidth'), ('MAC', 'MAC'), ('DC', 'Data Connectivity'), ('IPT', 'IPT - Internet Protocol Transit'), ('GGC', 'GGC - Google Global Cache'), ('FNA', 'FNA - Facebook Network Appliance'), ('BDIX', 'BDIX - Bangladesh Internet Exchange'), ('CDN', 'CDN - Content Delivery Network')], max_length=10),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='upstream_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='feasibility.upstreamprovider', verbose_name='Upstream Provider'),
        ),
    ]
