# Generated by Django 6.0.6 on 2026-08-17 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility', '0009_backfill_wo_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilityrequest',
            name='accounts_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='correction_from_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='link_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='Link ID'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='management_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='scr',
            field=models.CharField(blank=True, max_length=80, verbose_name='SCR'),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='tech_configured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_configured_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='tech_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='technical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feasibilityrequest',
            name='vlan_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='VLAN ID'),
        ),
        migrations.AlterField(
            model_name='feasibilityrequest',
            name='onboarding_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Accounts Review'), ('pending_approval', 'Pending Approval'), ('accounts_approved', 'Management Review'), ('management_approved', 'Technical Configuration'), ('tech_submitted', 'Technical Review'), ('correction_requested', 'Correction Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('provisioning', 'Provisioning'), ('activated', 'Activated'), ('closed', 'Closed')], max_length=32),
        ),
        migrations.CreateModel(
            name='WorkOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('accounts', 'Accounts'), ('management', 'Management'), ('core', 'Core / NTTN'), ('technical', 'Technical Team'), ('sales', 'Sales & Marketing')], max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('request_correction', 'Correction Requested'), ('submit_config', 'Configuration Submitted'), ('resubmit', 'Resubmitted')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_approvals', to='feasibility.feasibilityrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order Approval',
                'ordering': ['-created_at'],
            },
        ),
    ]
